### ISSUE TITLE
which button?? 

### ISSUE THREAD

**Issue by michabbb** [Syrian-Open-Source/laravel-package-template#2]
> To use this template, please click on button above "Use this template".

I don't see any button 🤔

**Comment by karam-mustafa** [comment]
Hi,
you don't see this button ??

![Screenshot 2022-01-27 133057](https://user-images.githubusercontent.com/71431942/151350787-f5dca7ad-796a-4ebc-b511-f6a8243703b8.png)

**Comment by michabbb** [comment]
ahhhhhhhhhhhh ☺
not on mobile or in the github app 🙈
my suggestion: you should add "(viewable only in desktop mode)" 😉

**Comment by karam-mustafa** [comment]
> ahhhhhhhhhhhh ☺ not on mobile or in the github app 🙈 my suggestion: you should add "(viewable only in desktop mode)" 😉

I will be happy if you make a pull request and add this suggestion

**Comment by michabbb** [comment]
> I will be happy if you make a pull request and add this suggestion

are you kidding me? so you don't have time adding 4 words, but you have time asking me to send a pull request instead - and I should take even more time creating a fork, make changes... commit and all that stuff... 

sometimes I am really wondering how lazy programmers can be.... holy sh....

**Comment by karam-mustafa** [comment]
> > I will be happy if you make a pull request and add this suggestion
> 
> are you kidding me? so you don't have time adding 4 words, but you have time asking me to send a pull request instead - and I should take even more time creating a fork, make changes... commit and all that stuff...
> 
> sometimes I am really wondering how lazy programmers can be.... holy sh....

Yes, I have time to add that but obviously I wanted you to share the development process with us, thank you
